### ISSUE TITLE
Configurable Events Endpoint

### ISSUE THREAD

**Issue by aljachimiak** [oddnetworks/oddworks-ios-tvos-sdk#9]
Looks like the events endpoint is currently hardcoded:
[https://github.com/oddnetworks/oddworks-ios-tvos-sdk/blob/master/OddSDK/OddEventsService.swift#L50](https://github.com/oddnetworks/oddworks-ios-tvos-sdk/blob/master/OddSDK/OddEventsService.swift#L50)

There is a setting available on the config endpoint:
`config.features.metrics.url = "https://analytics.oddworks.io/events"`

Can you please make the SDK take the events endpoint either:
- from the config (like android)

OR

- configurable in the Target plist?

Thanks!

**Comment by pmcconnell** [comment]
resolved with 0785fda51e49f83e711b5189345e1753aeb634ef
